In [18]:
# NumPy (Numerical Python) is a fundamental package for scientific computing in Python. 
# It provides support for large, multi-dimensional arrays and matrices, 
# along with a variety of functions to operate on these arrays efficiently. 
# In this explanation, I'll break down the key concepts and features of NumPy's arrays and 
# data structures with detailed examples.

In [19]:
# 1) Arrays: An array is a collection of elements of the same data type, 
# arranged in a grid of dimensions. It's the fundamental building block in NumPy.

In [ ]:
# You can create NumPy arrays using the numpy.array() function or 
# various specialized functions like numpy.zeros(), numpy.ones(), and numpy.arange().

In [68]:
import numpy as np

# Creating a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
# Here, a NumPy array is created from a Python list [1, 2, 3, 4, 5]. 
# The function np.array() is used to convert the list into a NumPy array. 
# The resulting array will contain the same elements as the list.
arr_1d

array([1, 2, 3, 4, 5])

In [69]:
# Creating a 2D array (matrix)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
# 2) Array Attributes: NumPy arrays have several attributes that 
#    provide information about their shape, data type, and more.

In [22]:
print(arr_2d.shape)  # Shape of the array (rows, columns)

(2, 3)


In [23]:
print(arr_2d.dtype)  # Data type of array elements

int32


In [24]:
# 3) Array Indexing and Slicing: You can access 
#    elements within an array using indexing and slicing.

In [25]:
print(arr_1d[2])          # Accessing a single element

3


In [26]:
print(arr_2d[1, 2])       # Accessing a specific element in a 2D array

6


In [27]:
print(arr_2d[:, 1])       # Slicing columns

[2 5]


In [28]:
print(arr_2d[1, :2])      # Slicing rows

[4 5]


In [29]:
# 4) Array Operations: NumPy enables element-wise operations and 
#    broadcasting, making computations efficient.

In [30]:
arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 5, 6])

In [31]:
# Element-wise addition
result = arr_a + arr_b
result

array([5, 7, 9])

In [32]:
# Broadcasting
result = arr_a + 10
result

array([11, 12, 13])

In [33]:
# 5) Universal Functions (ufuncs): NumPy provides a wide range of mathematical and 
#    logical functions that operate element-wise on arrays.

In [59]:
# Create an array of angles in radians
angles = np.array([0, np.pi/2, np.pi])
angles
# angles: [0.         1.57079633 3.14159265]
# Each element in the array represents an angle in radians:
# 0 radians (0 degrees), π/2 radians (90 degrees), and π radians (180 degrees)

array([0.        , 1.57079633, 3.14159265])

In [60]:
# Calculate the sine values of the angles
sines = np.sin(angles)
sines
# sines: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
# The np.sin() function computes the sine of each angle in the 'angles' array.
# The results are stored in the 'sines' array.

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [36]:
# Detailed explanation of calculations for each angle:
# Angle 0 radians (0 degrees):
# sin(0) = 0
# Result: 0.0000000e+00

In [37]:
# Angle π/2 radians (90 degrees):
# sin(π/2) = 1
# Result: 1.0000000e+00

In [38]:
# Angle π radians (180 degrees):
# sin(π) = 0
# Result: 1.2246468e-16
# Note: The result is not exactly 0 due to floating-point precision limitations.

In [39]:
# The 'sines' array now contains the sine values corresponding to the input angles.
# Note: The 'np.pi' constant represents the value of π (pi), which is approximately 3.14159265.
# End of code

In [40]:
# 6) Array Reshaping: You can reshape arrays while preserving data using the reshape function.

In [57]:
# Create a NumPy array with the values [1, 2, 3, 4, 5, 6]
flat_arr = np.array([1, 2, 3, 4, 5, 6])
flat_arr

array([1, 2, 3, 4, 5, 6])

In [58]:
# Reshape the flat_arr into a 2x3 matrix
matrix = flat_arr.reshape(2, 3)
matrix
# Now 'matrix' is a 2x3 matrix:

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
# Print the original flat array and the reshaped matrix
print("Original flat array:",(flat_arr))

Original flat array: [1 2 3 4 5 6]


In [49]:
print("Reshaped matrix:",(matrix))

Reshaped matrix: [[1 2 3]
 [4 5 6]]


In [ ]:
# 7) Array Concatenation and Splitting: NumPy allows you to combine or 
#    split arrays along specified axes.

In [53]:
# Create two arrays, arr1 and arr2
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
# Concatenate the two arrays along the first axis (row-wise concatenation)
combined = np.concatenate((arr1, arr2))
combined

array([1, 2, 3, 4, 5, 6])

In [54]:
# Create a 2x2 matrix (2D array)
matrix = np.array([[1, 2], [3, 4]])
matrix

array([[1, 2],
       [3, 4]])

In [56]:
# Split the matrix vertically into two submatrices
# The parameter 2 in np.vsplit indicates the number of equal parts to split the matrix into
top, bottom = np.vsplit(matrix, 2)
top, bottom

(array([[1, 2]]), array([[3, 4]]))

In [ ]:
# 8) Array Aggregations: You can perform aggregation operations like sum, mean, min, max, etc., 
#    on arrays.

In [61]:
# Create a 2D NumPy array with two rows and three columns
data = np.array([[1, 2, 3], [4, 5, 6]])
data

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
# Calculate the sum of all elements in the 'data' array
total_sum = np.sum(data)
total_sum

21

In [63]:
# Calculate the sum of elements along the columns (axis 0) of the 'data' array
column_sums = np.sum(data, axis=0)
column_sums

array([5, 7, 9])

In [ ]:
# 9) Boolean Indexing and Filtering: Boolean indexing allows you to select elements based on 
#    conditions.

In [64]:
# Create an array with the given values: [10, 20, 30, 40, 50]
data = np.array([10, 20, 30, 40, 50])
data

array([10, 20, 30, 40, 50])

In [65]:
# Create a new array containing only the elements from 'data' that are greater than 30
filtered = data[data > 30]
filtered

array([40, 50])

In [ ]:
# 10) Random Number Generation: NumPy provides functions for generating random numbers from 
#     various distributions.

In [66]:
# Generate an array of 5 random values from a uniform distribution between 0 and 1
random_values = np.random.rand(5)  # Uniform distribution
# This line generates an array random_values containing 5 random values sampled 
# from a uniform distribution. The np.random.rand() function generates random 
# numbers between 0 (inclusive) and 1 (exclusive), resulting in an even distribution of values.
random_values

array([0.58850866, 0.30135705, 0.28881451, 0.73315577, 0.96777237])

In [67]:
# Generate an array of 100 random values from a Gaussian (normal) distribution
# with a mean (loc) of 0 and a standard deviation (scale) of 1
gaussian_values = np.random.normal(0, 1, 100)  # Gaussian distribution
# This line generates an array gaussian_values containing 100 random values sampled 
# from a Gaussian (normal) distribution. The np.random.normal() function generates 
# random numbers following a Gaussian distribution with the specified 
# mean (average) of 0 and standard deviation (a measure of how spread out the values are) 
# of 1. This distribution is often called the standard normal distribution.
gaussian_values

array([ 1.18549502e+00,  5.84472053e-01,  2.34403934e-01,  4.58443390e-01,
       -4.61962165e-01,  1.05270359e+00,  6.34098389e-02, -2.52809695e-01,
       -2.82761442e-01,  5.06831023e-01, -9.84260993e-01, -7.97015398e-01,
       -2.21974101e-01, -7.27829548e-01,  9.53962585e-01, -9.46847631e-02,
       -6.41164329e-03, -1.29984196e-03,  1.19648537e+00, -1.88934955e+00,
        2.00995979e+00,  6.81459935e-01,  4.94348239e-01, -1.06687269e-01,
        9.48218250e-01,  7.98274359e-01,  2.29236090e-01, -9.16886347e-02,
        1.10065650e+00,  5.28131571e-01,  1.09266905e+00,  4.05581278e-01,
        1.24846652e-02, -1.85270942e-01, -2.06080081e-01, -2.41860874e-01,
        1.96402552e-01,  4.04729789e-01,  1.20983873e+00, -1.61061707e-01,
       -1.31074519e+00,  2.93620824e+00, -2.09145510e-01, -5.13314456e-01,
        1.48946957e-01,  5.98132066e-01, -2.98039279e-01,  1.78258340e+00,
        1.83925872e+00,  2.74766194e-01,  4.61537011e-01,  7.68714316e-01,
       -1.80574851e-01,  