In [ ]:
# 1) Element-wise Operations: NumPy allows performing element-wise operations on arrays, 
#             applying an operation to each corresponding element in two or more arrays.

In [ ]:
import numpy as np  # Import the NumPy library for numerical operations

In [8]:
# Create NumPy arrays 'a' and 'b' with the given values
a = np.array([1, 2, 3])  # 'a' is [1, 2, 3]
b = np.array([4, 5, 6])  # 'b' is [4, 5, 6]

# Element-wise addition: Add corresponding elements of arrays 'a' and 'b'
add_result = a + b  # 'add_result' is [5, 7, 9]
# Explanation: Each element of 'add_result' is the sum of the corresponding elements of 'a' and 'b'.
# 1 + 4 = 5, 2 + 5 = 7, 3 + 6 = 9
add_result

array([5, 7, 9])

In [9]:
# Element-wise multiplication: Multiply corresponding elements of arrays 'a' and 'b'
multiply_result = a * b  # 'multiply_result' is [4, 10, 18]
# Explanation: Each element of 'multiply_result' is the product of 
# the corresponding elements of 'a' and 'b'.
# 1 * 4 = 4, 2 * 5 = 10, 3 * 6 = 18
multiply_result

array([ 4, 10, 18])

In [ ]:
# 2) Broadcasting: NumPy supports broadcasting, which allows performing operations on 
#                  arrays of different shapes by automatically expanding dimensions.

In [10]:
# Create a 2-dimensional numpy array 'a' with shape (2, 3)
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
# Create a 1-dimensional numpy array 'b' with values [10, 20, 30]
b = np.array([10, 20, 30])
b

array([10, 20, 30])

In [12]:
# Broadcasting: Add array 'b' to each row of array 'a'
# Since 'a' has shape (2, 3) and 'b' has shape (3,), numpy automatically broadcasts 'b' to 
# match the shape of 'a'
# Broadcasting allows numpy to perform element-wise operations even when arrays 
# have different shapes
result = a + b  # The result will be a new numpy array with the same shape as 'a' 
# where each element is the sum of the corresponding elements in 'a' and 'b'
result
# The resulting array 'result' will be:
# [[1 + 10, 2 + 20, 3 + 30],
#  [4 + 10, 5 + 20, 6 + 30]]
# which simplifies to:
# [[11, 22, 33],
#  [14, 25, 36]]

array([[11, 22, 33],
       [14, 25, 36]])

In [ ]:
# 3) Universal Functions (ufuncs): NumPy provides a wide range of built-in mathematical functions 
#                                  (ufuncs) that can be applied element-wise to arrays.

In [13]:
# Create a NumPy array containing the values [1, 2, 3, 4].
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [14]:
# Calculate the square root of each element in the 'arr' array.
# The np.sqrt() function is a universal function (ufunc) that operates element-wise on arrays.
# It returns a new array where each element is the square root of the corresponding element in 'arr'.
sqrt_arr = np.sqrt(arr)  # Result: [1.0, 1.414, 1.732, 2.0]
sqrt_arr

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [15]:
# Calculate the exponential function e^x for each element in the 'arr' array.
# The np.exp() function is another universal function (ufunc) that calculates the exponential for each element.
# It returns a new array where each element is e raised to the power of the corresponding element in 'arr'.
exp_arr = np.exp(arr)  # Result: [2.718, 7.389, 20.085, 54.598]
exp_arr

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [ ]:
# 4) Aggregation Functions: NumPy offers aggregation functions like numpy.sum(), 
#         numpy.mean(), numpy.max(), etc., to compute summary statistics of arrays.

In [16]:
# Create a 2D NumPy array (matrix) with 2 rows and 3 columns
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
# Aggregation functions Calculate the sum of all elements in the entire array
sum_all = np.sum(arr)  # Result: 1 + 2 + 3 + 4 + 5 + 6 = 21
sum_all

21

In [18]:
# Calculate the mean (average) of elements along axis 0 (columns)
# Axis 0 represents the vertical columns in a 2D array
mean_axis0 = np.mean(arr, axis=0)
# For axis 0: (1 + 4) / 2 = 2.5, (2 + 5) / 2 = 3.5, (3 + 6) / 2 = 4.5
# Result: [2.5, 3.5, 4.5]
mean_axis0

array([2.5, 3.5, 4.5])

In [19]:
# Calculate the maximum element along axis 1 (rows)
# Axis 1 represents the horizontal rows in a 2D array
max_axis1 = np.max(arr, axis=1)
# For axis 1: Maximum of [1, 2, 3] = 3, Maximum of [4, 5, 6] = 6
# Result: [3, 6]
max_axis1

array([3, 6])

In [ ]:
# 5) Array Manipulation: NumPy provides functions to reshape, concatenate, and split arrays.

In [35]:
# Create a 2x3 numpy array
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
# Reshape the array to a 3x2 array
reshaped = arr.reshape(3, 2)  # reshaped: [[1, 2], [3, 4], [5, 6]]
reshaped

array([[1, 2],
       [3, 4],
       [5, 6]])